version: "2.3"

services:

  db_postgres:
    image: postgres
    environment:
     POSTGRES_PASSWORD: password
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
    ports:
     - 5432:5432

  db_postgres_admin:
    image: dpage/pgadmin4
    environment:
     PGADMIN_DEFAULT_PASSWORD: "password"
     PGADMIN_DEFAULT_EMAIL: "mail@mail.com"
    ports:
     - 5000:80
